apiVersion: v1
kind: Service
metadata:
  name: nielskrijger-blog
  labels:
    app: nielskrijger-blog
    tier: front-end
spec:
  type: LoadBalancer
  loadBalancerIP: 35.185.73.16
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: nielskrijger-blog
    tier: front-end
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nielskrijger-blog
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nielskrijger-blog
        tier: front-end
    spec:
      containers:
        - name: nielskrijger-blog
          image: us.gcr.io/metrix-io/nielskrijger-blog:master
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: production
